# .github/workflows/build.yml
name: Build Cross-Platform Executables

on:
  push:
    tags:
      - 'v*'  # v1.0.0 같은 태그 푸시 시 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: korean-pdf-converter.exe
            build_command: pyinstaller --onefile --windowed --name "korean-pdf-converter" korean_pdf_converter.py
          - os: macos-latest
            artifact_name: korean-pdf-converter
            build_command: pyinstaller --onefile --windowed --name "korean-pdf-converter" korean_pdf_converter.py
          - os: ubuntu-latest
            artifact_name: korean-pdf-converter
            build_command: pyinstaller --onefile --name "korean-pdf-converter" korean_pdf_converter.py

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyPDF2 pdfplumber PyMuPDF pdfminer.six pyinstaller
    
    - name: Build executable
      run: ${{ matrix.build_command }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-executable
        path: |
          dist/${{ matrix.artifact_name }}
          dist/${{ matrix.artifact_name }}.app
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}